### ISSUE TITLE
Reduce memory footprint of sprite rendering

### ISSUE THREAD

**Issue by Fordi** [Fordi/UcPPU#1]
Because of the nature of the render loop and memory constraints on the device, the render loop is a per-scanline job.  As a result, the initial implementation looped through each sprite for each scanline.

This was inefficient, so it was changed to loop through the sprites once, filling a table with the sprites that are on each scanline.  Unfortunately, while this is cycle-efficient, it's not memory-efficient, as UCPPU_HEIGHT bytes are needed for each possible entry per scanline.  So if the lib is configured to support 32 sprites per scanline, the table holding references is 4k in size.  Thats... a bit much.

A big improvement would be to dynamically allocate as needed - predictively would be best - but my first attempt was a segfaulting failure.  Anyway, note to self: make this work, stupid.

**Comment by Rohansi** [comment]
I don't have the hardware but you could sort the sprites by their starting scanline, possibly just storing their index rather than a sorted copy of the whole array. This makes it easy to find all the sprites on each scanline (binary search for finding a specific line, but can also just keep a starting index variable for your loop) and only needs to be done once per frame.

It should be a stable sorting algorithm so you don't risk unintentional flickering when many sprites are on the same scanline. 

You could also attempt to reduce overdraw by reading the sorted sprites in reverse.

**Comment by Fordi** [comment]
That's a good idea - though, if I'm just going to do a binary search on the results of the sort, just making a b-tree without re-integrating the sort would probably work.

In terms of stability - and this is a note to self now - I'd want earlier indices to be drawn earlier for any given scanline, so that the developer can rely on higher-indexed sprites to be drawn on top.

I've not been actively developing on this for a while - perhaps it's time to get back to it.  At the very least, I can implement in JS first so I have a handle on the algorithm without dealing with memory management.

Thanks for the suggestion!
